name: Deployment

on: [push]

jobs:
  # Build with unity
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Cleaning for space
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true # Removes unused tools
          android-sdk: true # Frees Android bloat

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v5
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - name: Restore Unity Cache
        uses: actions/cache@v5
        with:
          path: Library
          key: ${{ runner.os }}-Library-${{ hashFiles('Packages/**', 'ProjectSettings/**') }}

      # Build
      # This will place the build in "build" folder
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      # Upload the build output as an artifact for deploy job
      # Idk why unity put duplicate "WebGL" folder name as parent and children folder
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/WebGL
  
  # Deploy to itch.io using Butler
  deploy:
    name: Deploy the project
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the build artifact from the build job
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: build
          path: build
          
      # Deploy to itch io
      - name: Deploy to itch.io
        uses: yeslayla/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
          CHANNEL: webgl
          ITCH_GAME: ${{ vars.ITCHIO_GAME_NAME }}
          ITCH_USER: ${{ vars.ITCHIO_USERNAME }}
          PACKAGE: build
